#ifndef ads_CoreFragments_h
#define ads_CoreFragments_h

// Enumeration with all fragments of this form
enum
{
    ads_CoreStepEigenSolverFragment,
    ads_CoreSectionFragment,
    ads_CoreCfdStepFragment,
    ads_CoreStepsFragment,
    ads_CoreProfileLibraryFragment,
    ads_CoreResultsFragment,
    ads_CoreFieldFragment,
    ads_CoreDiagnosticsFragment,
    ads_CoreStepTimeIncrementFragment,
    ads_CorePropertyGeneralFragment,
    ads_CorePropertyElasticStructFragment,
    ads_CorePropertyThermalFragment,
    ads_CorePropertyUniaxialFragment,
    ads_CoreTasksFragment,
    ads_CoreMatLegacyPropertiesFragment,
    ads_CoreFiltersFragment,
    ads_CoreConnectorLibraryFragment,
    ads_CoreConnectorTableFragment,
    ads_CorePropertyDamageFragment,
    ads_CorePropertyOtherFragment,
    ads_CorePropertyPlasticFragment,
    ads_CorePropertyViscoFragment,
    ads_CoreInfrastructureFragment,
    ads_CoreOrientationsFragment,
    ads_CoreFESystemFragment,
    ads_CoreInteractionsFragment,
    ads_CoreMicrotopologyFragment,
    ads_CoreConnectorDofFragment,
    ads_CoreFocusFragment,
    ads_CoreConstraintsFragment,
    ads_CoreInteractionsContactFragment,
    ads_CoreContourFragment,
    ads_CoreCosimulationFragment,
    ads_CoreSteadyStateIncFragment,
    ads_CoreTransientIncFragment,
    ads_CoreCurveFragment,
    ads_CoreMeshFragment,
    ads_CoreEventsFragment,
    ads_CoreRegionFragment,
    ads_CoreModelFragment,
    ads_CoreExcitationFragment,
    ads_CoreUnitFragment,
    ads_CoreParameterFragment,
    ads_CoreMaterialLibraryFragment,
    ads_CorePropertyTableFragment,
    ads_CorePropertyMultiPhysicsFragment,
    ads_CoreDisassemblyFragment,
    ads_CoreDisassemblyOldFragment,
    ads_CoreInternalDataFragment,
    ads_CoreMatLegacyPropertiesOldFragment,
    ads_CoreLayerFragment,
    ads_CoreLocalSysFragment,
    ads_CorePropertyConcreteFragment,
    ads_CorePropertyCreepFragment,
    ads_CorePropertyElasticOtherFragment,
    ads_CorePropertyElasticHyperFragment,
    ads_CorePropertyElasticLinearFragment,
    ads_CoreSurfaceFragment,
    ads_CoreOutputRequestsFragment,
    ads_CorePropertyHighLevelFragment,
    ads_CoreSectionPropFragment,
    ads_CoreMicrotopologyOldFragment
};

int ads_CoreFragmentTypeIndex(int fragment, int fragmentTypeIndex);

#endif
