/*   -*- mode: c++ -*-   */
#ifndef inp_Visitor_h
#define inp_Visitor_h

///////////////////////////////////////////////////////////////////////////////
//
// File Name: inp_Visitor.h
//
// Description:  
//

// Includes

// Forward declarations

// Begin local includes
#include <mem_AllocationOperators.h>

#include <inp_Keyword.h>
#include <cow_ListInt.h>
#include <cow_ListTranslatedString.h>
#include <cow_Map.h>

// Class definition

class inp_Visitor  : public mem_AllocationOperators
{
  public:

    inp_Visitor();
    virtual ~inp_Visitor();

    virtual void VisitList(inp_KeywordList&);
    virtual void Report() const;
    virtual void VisitListAndReport(inp_KeywordList&);
    virtual void Visit(inp_Keyword&);
    virtual void VisitSuboptions(inp_Keyword&);
    virtual void DefaultAction(inp_Keyword&) = 0;

    bool IsError() const;
    bool IsWarning() const;

    atr_String Errors() const;
    atr_String Warnings() const;
    atr_String FatalErrors() const;

    const cow_ListTranslatedString& GetErrorList()   const { return errors; }
    const cow_ListTranslatedString& GetWarningList() const { return warnings; }
    const cow_ListTranslatedString& GetFatalErrorList()   const { return fatalErrors; }

    void SetAssemblyName(const inp_Keyword&);
    void SetInstanceName(const inp_Keyword&);
    void SetPartName(const inp_Keyword&);
    void SetStepName(const inp_Keyword&);
    void ClearAssemblyName() { currentAssemblyName.Erase(); }
    void ClearInstanceName() { currentInstanceName.Erase(); }
    void ClearPartName() { currentPartName.Erase(); }
    void ClearStepName() { currentStepName.Erase(); }

    // Functions for completing parameters/enums/data in specific keywords

	virtual void VisitAcousticFlowVelocity(inp_Keyword&);
    virtual void VisitAcousticWaveFormulation(inp_Keyword&);
    virtual void VisitAcousticMedium(inp_Keyword&);
    virtual void VisitAdaptiveMesh(inp_Keyword&);
    virtual void VisitAdaptiveMeshConstraint(inp_Keyword&);
    virtual void VisitAdaptiveMeshControls(inp_Keyword&);
    virtual void VisitAdjust(inp_Keyword&);
    virtual void VisitAmplitude(inp_Keyword&);
    virtual void VisitAnisotropicHyperelastic(inp_Keyword&);
    virtual void VisitAnneal(inp_Keyword&);
    virtual void VisitAnnealTemperature(inp_Keyword&);
    virtual void VisitAqua(inp_Keyword&);
    virtual void VisitAssembly(inp_Keyword&);
    virtual void VisitAsymmetricAxisymmetric(inp_Keyword&);
    virtual void VisitAxial(inp_Keyword&);
    virtual void VisitBaselineCorrection(inp_Keyword&);
    virtual void VisitBaseMotion(inp_Keyword&);
    virtual void VisitBeamAddedInertia(inp_Keyword&);
    virtual void VisitBeamFluidInertia(inp_Keyword&);
    virtual void VisitBeamGeneralSection(inp_Keyword&);
    virtual void VisitBeamSection(inp_Keyword&);
    virtual void VisitBeamSectionGenerate(inp_Keyword&);
    virtual void VisitBiaxial(inp_Keyword&);
    virtual void VisitBiaxialTestData(inp_Keyword&);
    virtual void VisitBlockage(inp_Keyword&);
    virtual void VisitBond(inp_Keyword&);
    virtual void VisitBoundary(inp_Keyword&);
    virtual void VisitBrittleCracking(inp_Keyword&);
    virtual void VisitBrittleFailure(inp_Keyword&);
    virtual void VisitBrittleShear(inp_Keyword&);
    virtual void VisitBuckle(inp_Keyword&);
    virtual void VisitBucklingEnvelope(inp_Keyword&);
    virtual void VisitBucklingLength(inp_Keyword&);
    virtual void VisitBucklingReductionFactors(inp_Keyword&);
    virtual void VisitBulkViscosity(inp_Keyword&);
    virtual void VisitCAddedMass(inp_Keyword&);
    virtual void VisitCapacity(inp_Keyword&);
    virtual void VisitCapCreep(inp_Keyword&);
    virtual void VisitCapHardening(inp_Keyword&);
    virtual void VisitCapPlasticity(inp_Keyword&);
    virtual void VisitCastIronCompressionHardening(inp_Keyword&);
    virtual void VisitCastIronPlasticity(inp_Keyword&);
    virtual void VisitCastIronTensionHardening(inp_Keyword&);
    virtual void VisitCavityDefinition(inp_Keyword&);
    virtual void VisitCecharge(inp_Keyword&);
    virtual void VisitCecurrent(inp_Keyword&);
    virtual void VisitCentroid(inp_Keyword&);
    virtual void VisitCfd(inp_Keyword&);
    virtual void VisitCfilm(inp_Keyword&);
    virtual void VisitCflow(inp_Keyword&);
    virtual void VisitCflux(inp_Keyword&);
    virtual void VisitChangeFriction(inp_Keyword&);
    virtual void VisitClayHardening(inp_Keyword&);
    virtual void VisitClayPlasticity(inp_Keyword&);
    virtual void VisitClearance(inp_Keyword&);
    virtual void VisitCload(inp_Keyword&);
    virtual void VisitCohesiveBehavior(inp_Keyword&);
    virtual void VisitCohesiveSection(inp_Keyword&);
    virtual void VisitCombinedTestData(inp_Keyword&);
    virtual void VisitComplexFrequency(inp_Keyword&);
    virtual void VisitConcrete(inp_Keyword&);
    virtual void VisitConcreteCompressionDamage(inp_Keyword&);
    virtual void VisitConcreteCompressionHardening(inp_Keyword&);
    virtual void VisitConcreteDamagedPlasticity(inp_Keyword&);
    virtual void VisitConcreteTensionDamage(inp_Keyword&);
    virtual void VisitConcreteTensionStiffening(inp_Keyword&);
    virtual void VisitConductivity(inp_Keyword&);
    virtual void VisitConductionEquationSolver(inp_Keyword&);
    virtual void VisitConflicts(inp_Keyword&);
    virtual void VisitConnectorSection(inp_Keyword&);
    virtual void VisitConnectorBehavior(inp_Keyword&);
    virtual void VisitConnectorConstitutiveReference(inp_Keyword&);
    virtual void VisitConnectorContactForce(inp_Keyword&);
    virtual void VisitConnectorDamageEvolution(inp_Keyword&);
    virtual void VisitConnectorDamageInitiation(inp_Keyword&);
    virtual void VisitConnectorDamping(inp_Keyword&);
    virtual void VisitConnectorDerivedComponent(inp_Keyword&);
    virtual void VisitConnectorElasticity(inp_Keyword&);
    virtual void VisitConnectorFailure(inp_Keyword&);
    virtual void VisitConnectorFriction(inp_Keyword&);
    virtual void VisitConnectorHardening(inp_Keyword&);
    virtual void VisitConnectorLoad(inp_Keyword&);
    virtual void VisitConnectorLock(inp_Keyword&);
    virtual void VisitConnectorMotion(inp_Keyword&);
    virtual void VisitConnectorPlasticity(inp_Keyword&);
    virtual void VisitConnectorPotential(inp_Keyword&);
    virtual void VisitConnectorStop(inp_Keyword&);
    virtual void VisitConnectorUniaxialBehavior(inp_Keyword&);
    virtual void VisitConstraintControls(inp_Keyword&);
    virtual void VisitContact(inp_Keyword&);
    virtual void VisitContactClearance(inp_Keyword&);
    virtual void VisitContactClearanceAssignment(inp_Keyword&);
    virtual void VisitContactControls(inp_Keyword&);
    virtual void VisitContactControlsAssignment(inp_Keyword&);
    virtual void VisitContactDamping(inp_Keyword&);
    virtual void VisitContactExclusions(inp_Keyword&);
    virtual void VisitContactFile(inp_Keyword&);
    virtual void VisitContactFormulation(inp_Keyword&);
    virtual void VisitContactInclusions(inp_Keyword&);
    virtual void VisitContactInitializationAssignment(inp_Keyword&);
    virtual void VisitContactInitializationData(inp_Keyword&);
    virtual void VisitContactInterference(inp_Keyword&);
    virtual void VisitContactOutput(inp_Keyword&);
    virtual void VisitContactPair(inp_Keyword&);
    virtual void VisitContactPermeability(inp_Keyword&);
    virtual void VisitContactPrint(inp_Keyword&);
    virtual void VisitContactPropertyAssignment(inp_Keyword&);
    virtual void VisitContactResponse(inp_Keyword&);
    virtual void VisitContactStabilization(inp_Keyword&);
    virtual void VisitContourIntegral(inp_Keyword&);
    virtual void VisitControls(inp_Keyword&);
    virtual void VisitConwepChargeProperty(inp_Keyword&);
    virtual void VisitCorrelation(inp_Keyword&);
    virtual void VisitCoupledTemperatureDisplacement(inp_Keyword&);
    virtual void VisitCoupledThermalElectrical(inp_Keyword&);
    virtual void VisitCoSimulation(inp_Keyword&);
    virtual void VisitCoSimulationControls(inp_Keyword&);
    virtual void VisitCoSimulationRegion(inp_Keyword&);
    virtual void VisitCoupling(inp_Keyword&);
    virtual void VisitCradiate(inp_Keyword&);
    virtual void VisitCreep(inp_Keyword&);
    virtual void VisitCreepStrainRateControl(inp_Keyword&);
    virtual void VisitCrushableFoam(inp_Keyword&);
    virtual void VisitCrushableFoamHardening(inp_Keyword&);
    virtual void VisitCycledPlastic(inp_Keyword&);
    virtual void VisitCyclic(inp_Keyword&);
    virtual void VisitCyclicHardening(inp_Keyword&);
    virtual void VisitCyclicSymmetryModel(inp_Keyword&);
    virtual void VisitDAddedMass(inp_Keyword&);
    virtual void VisitDamageEvolution(inp_Keyword&);
    virtual void VisitDamageInitiation(inp_Keyword&);
    virtual void VisitDamageStabilization(inp_Keyword&);
    virtual void VisitDamping(inp_Keyword&);
    virtual void VisitDampingControls(inp_Keyword&);
    virtual void VisitDashpot(inp_Keyword&);
    virtual void VisitDebond(inp_Keyword&);
    virtual void VisitDecharge(inp_Keyword&);
    virtual void VisitDecurrent(inp_Keyword&);
    virtual void VisitDeformationPlasticity(inp_Keyword&);
    virtual void VisitDEmPotential(inp_Keyword&);
    virtual void VisitDensity(inp_Keyword&);
    virtual void VisitDepvar(inp_Keyword&);
    virtual void VisitDesignParameter(inp_Keyword&);
    virtual void VisitDesignResponse(inp_Keyword&);
    virtual void VisitDesignShapeVariation(inp_Keyword&);
    virtual void VisitDesignValue(inp_Keyword&);
    virtual void VisitDesignVariation(inp_Keyword&);
    virtual void VisitDetonationPoint(inp_Keyword&);
    virtual void VisitDflow(inp_Keyword&);
    virtual void VisitDflux(inp_Keyword&);
    virtual void VisitDiagnostics(inp_Keyword&);
    virtual void VisitDielectric(inp_Keyword&);
    virtual void VisitDiffusivity(inp_Keyword&);
    virtual void VisitDirectCyclic(inp_Keyword&);
    virtual void VisitDiscreteSection(inp_Keyword&);
    virtual void VisitDiscreteInteraction(inp_Keyword&);
    virtual void VisitDiscreteInteractionProperty(inp_Keyword&);
    virtual void VisitDisplayBody(inp_Keyword&);
    virtual void VisitDistributing(inp_Keyword&);
    virtual void VisitDistributingCoupling(inp_Keyword&);
    virtual void VisitDistribution(inp_Keyword&);
    virtual void VisitDistributionTable(inp_Keyword&);
    virtual void VisitDload(inp_Keyword&);
    virtual void VisitDragChain(inp_Keyword&);
    virtual void VisitDruckerPrager(inp_Keyword&);
    virtual void VisitDruckerPragerCreep(inp_Keyword&);
    virtual void VisitDruckerPragerHardening(inp_Keyword&);
    virtual void VisitDsaControls(inp_Keyword&);
    virtual void VisitDsecharge(inp_Keyword&);
    virtual void VisitDsecurrent(inp_Keyword&);
    virtual void VisitDsflow(inp_Keyword&);
    virtual void VisitDsflux(inp_Keyword&);
    virtual void VisitDsload(inp_Keyword&);
    virtual void VisitDynamic(inp_Keyword&);
    virtual void VisitDynamicTemperatureDisplacement(inp_Keyword&);
    virtual void VisitElastic(inp_Keyword&);
    virtual void VisitElcopy(inp_Keyword&);
    virtual void VisitElectricalConductivity(inp_Keyword&);
    virtual void VisitElectromagnetic(inp_Keyword&);
    virtual void VisitElement(inp_Keyword&);
    virtual void VisitElementMatrixOutput(inp_Keyword&);
    virtual void VisitElementOutput(inp_Keyword&);
    virtual void VisitElementRecoveryMatrix(inp_Keyword&);
    virtual void VisitElementResponse(inp_Keyword&);
    virtual void VisitElFile(inp_Keyword&);
    virtual void VisitElgen(inp_Keyword&);
    virtual void VisitElPrint(inp_Keyword&);
    virtual void VisitElset(inp_Keyword&);
    virtual void VisitEmbeddedElement(inp_Keyword&);
    virtual void VisitEmissivity(inp_Keyword&);
    virtual void VisitEndAssembly(inp_Keyword&);
    virtual void VisitEndInstance(inp_Keyword&);
    virtual void VisitEndLoadCase(inp_Keyword&);
    virtual void VisitEndPart(inp_Keyword&);
    virtual void VisitEndStep(inp_Keyword&);
    virtual void VisitEnergyFile(inp_Keyword&);
    virtual void VisitEnergyOutput(inp_Keyword&);
    virtual void VisitEnergyPrint(inp_Keyword&);
    virtual void VisitEnrichment(inp_Keyword&);
    virtual void VisitEnrichmentActivation(inp_Keyword&);
    virtual void VisitEos(inp_Keyword&);
    virtual void VisitEosCompaction(inp_Keyword&);
    virtual void VisitEosShear(inp_Keyword&);
    virtual void VisitEpjoint(inp_Keyword&);
    virtual void VisitEquation(inp_Keyword&);
  //    virtual void VisitEulerianCouping(inp_Keyword&);
    virtual void VisitEulerianBoundary(inp_Keyword&);
    virtual void VisitEulerianInflatorMixture(inp_Keyword&);
    virtual void VisitEulerianInflatorProperty(inp_Keyword&);
    virtual void VisitEulerianMeshMotion(inp_Keyword&);
    virtual void VisitEulerianSection(inp_Keyword&);
    virtual void VisitExpansion(inp_Keyword&);
    virtual void VisitExtremeElementValue(inp_Keyword&);
    virtual void VisitExtremeNodeValue(inp_Keyword&);
    virtual void VisitExtremeValue(inp_Keyword&);
    virtual void VisitFabric(inp_Keyword&);
    virtual void VisitFailure(inp_Keyword&);
    virtual void VisitFailureRatios(inp_Keyword&);
    virtual void VisitFailStrain(inp_Keyword&);
    virtual void VisitFailStress(inp_Keyword&);
    virtual void VisitFastener(inp_Keyword&);
    virtual void VisitFastenerFailure(inp_Keyword&);
    virtual void VisitFastenerProperty(inp_Keyword&);
    virtual void VisitField(inp_Keyword&);
    virtual void VisitFileFormat(inp_Keyword&);
    virtual void VisitFileOutput(inp_Keyword&);
    virtual void VisitFilm(inp_Keyword&);
    virtual void VisitFilmProperty(inp_Keyword&);
    virtual void VisitFilter(inp_Keyword&);
    virtual void VisitFixedMassScaling(inp_Keyword&);
    virtual void VisitFlow(inp_Keyword&);
    virtual void VisitFluidBehavior(inp_Keyword&);
    virtual void VisitFluidBoundary(inp_Keyword&);
    virtual void VisitFluidBulkModulus(inp_Keyword&);
    virtual void VisitFluidCavity(inp_Keyword&);
    virtual void VisitFluidDensity(inp_Keyword&);
    virtual void VisitFluidExchange(inp_Keyword&);
    virtual void VisitFluidExchangeActivation(inp_Keyword&);
    virtual void VisitFluidExchangeInteraction(inp_Keyword&);
    virtual void VisitFluidExchangeProperty(inp_Keyword&);
    virtual void VisitFluidExpansion(inp_Keyword&);
    virtual void VisitFluidFlux(inp_Keyword&);
    virtual void VisitFluidInflator(inp_Keyword&);
    virtual void VisitFluidInflatorActivation(inp_Keyword&);
    virtual void VisitFluidInflatorInteraction(inp_Keyword&);
    virtual void VisitFluidInflatorMixture(inp_Keyword&);
    virtual void VisitFluidInflatorProperty(inp_Keyword&);
    virtual void VisitFluidLeakoff(inp_Keyword&);
    virtual void VisitFluidLink(inp_Keyword&);
    virtual void VisitFluidProperty(inp_Keyword&);
    virtual void VisitFoam(inp_Keyword&);
    virtual void VisitFoundation(inp_Keyword&);
    virtual void VisitFoamHardening(inp_Keyword&);
    virtual void VisitFractureCriterion(inp_Keyword&);
    virtual void VisitFrameSection(inp_Keyword&);
    virtual void VisitFrequency(inp_Keyword&);
    virtual void VisitFriction(inp_Keyword&);
    virtual void VisitGap(inp_Keyword&);
    virtual void VisitGapConductance(inp_Keyword&);
    virtual void VisitGapElectricalConductance(inp_Keyword&);
    virtual void VisitGapHeatGeneration(inp_Keyword&);
    virtual void VisitGapFlow(inp_Keyword&);
    virtual void VisitGapRadiation(inp_Keyword&);
    virtual void VisitGasketBehavior(inp_Keyword&);
    virtual void VisitGasketContactArea(inp_Keyword&);
    virtual void VisitGasketElasticity(inp_Keyword&);
    virtual void VisitGasketSection(inp_Keyword&);
    virtual void VisitGasketThicknessBehavior(inp_Keyword&);
    virtual void VisitGasSpecificHeat(inp_Keyword&);
    virtual void VisitGel(inp_Keyword&);
    virtual void VisitGeostatic(inp_Keyword&);
    virtual void VisitGlobalDamping(inp_Keyword&);
    virtual void VisitHeading(inp_Keyword&);
    virtual void VisitHeatCap(inp_Keyword&);
    virtual void VisitHeatGeneration(inp_Keyword&);
    virtual void VisitHeatTransfer(inp_Keyword&);
    virtual void VisitHourglassStiffness(inp_Keyword&);
    virtual void VisitHyperelastic(inp_Keyword&);
    virtual void VisitHyperfoam(inp_Keyword&);
    virtual void VisitHypoelastic(inp_Keyword&);
    virtual void VisitHysteresis(inp_Keyword&);
    virtual void VisitImpedance(inp_Keyword&);
    virtual void VisitImpedanceProperty(inp_Keyword&);
    virtual void VisitImperfection(inp_Keyword&);
    virtual void VisitImport(inp_Keyword&);
    virtual void VisitImportControls(inp_Keyword&);
    virtual void VisitImportElset(inp_Keyword&);
    virtual void VisitImportNset(inp_Keyword&);
    virtual void VisitIncidentWave(inp_Keyword&);
    virtual void VisitIncidentWaveInteraction(inp_Keyword&);
    virtual void VisitIncidentWaveInteractionProperty(inp_Keyword&);
    virtual void VisitIncidentWaveProperty(inp_Keyword&);
    virtual void VisitIncidentWaveReflection(inp_Keyword&);
    virtual void VisitIncidentWaveFluidProperty(inp_Keyword&);
    virtual void VisitInclude(inp_Keyword&);
    virtual void VisitIncrementationOutput(inp_Keyword&);
    virtual void VisitInelasticHeatFraction(inp_Keyword&);
    virtual void VisitInertiaRelief(inp_Keyword&);
    virtual void VisitInitialConditions(inp_Keyword&);
    virtual void VisitInstance(inp_Keyword&);
    virtual void VisitIntegratedOutput(inp_Keyword&);
    virtual void VisitIntegratedOutputSection(inp_Keyword&);
    virtual void VisitInterface(inp_Keyword&);
    virtual void VisitIts(inp_Keyword&);
    virtual void VisitJoint(inp_Keyword&);
    virtual void VisitJointedMaterial(inp_Keyword&);
    virtual void VisitJointElasticity(inp_Keyword&);
    virtual void VisitJointPlasticity(inp_Keyword&);
    virtual void VisitJouleHeatFraction(inp_Keyword&);
    virtual void VisitKappa(inp_Keyword&);
    virtual void VisitKinematic(inp_Keyword&);
    virtual void VisitKinematicCoupling(inp_Keyword&);
    virtual void VisitLatentHeat(inp_Keyword&);
    virtual void VisitLicense(inp_Keyword&);
    virtual void VisitLoadCase(inp_Keyword&);
    virtual void VisitLoadingData(inp_Keyword&);
    virtual void VisitLowDensityFoam(inp_Keyword&);
    virtual void VisitM1(inp_Keyword&);
    virtual void VisitM2(inp_Keyword&);
    virtual void VisitMagneticPermeability(inp_Keyword&);
    virtual void VisitMapSolution(inp_Keyword&);
    virtual void VisitMass(inp_Keyword&);
    virtual void VisitMassAdjust(inp_Keyword&);
    virtual void VisitMassDiffusion(inp_Keyword&);
    virtual void VisitMassFlowRate(inp_Keyword&);
    virtual void VisitMaterial(inp_Keyword&);
    virtual void VisitMatrix(inp_Keyword&);
    virtual void VisitMatrixAssemble(inp_Keyword&);
    virtual void VisitMatrixGenerate(inp_Keyword&);
    virtual void VisitMatrixInput(inp_Keyword&);
    virtual void VisitMatrixOutput(inp_Keyword&);
    virtual void VisitMediaTransport(inp_Keyword&);
    virtual void VisitMembraneSection(inp_Keyword&);
    virtual void VisitModalDamping(inp_Keyword&);
    virtual void VisitModalDynamic(inp_Keyword&);
    virtual void VisitModalFile(inp_Keyword&);
    virtual void VisitModalOutput(inp_Keyword&);
    virtual void VisitModelChange(inp_Keyword&);
    virtual void VisitMohrCoulomb(inp_Keyword&);
    virtual void VisitMohrCoulombHardening(inp_Keyword&);
    virtual void VisitMoistureSwelling(inp_Keyword&);
    virtual void VisitMolecularWeight(inp_Keyword&);
    virtual void VisitMomentumEquationSolver(inp_Keyword&);
    virtual void VisitMonitor(inp_Keyword&);
    virtual void VisitMotion(inp_Keyword&);
    virtual void VisitMpc(inp_Keyword&);
    virtual void VisitMullinsEffect(inp_Keyword&);
    virtual void VisitNcopy(inp_Keyword&);
    virtual void VisitNfill(inp_Keyword&);
    virtual void VisitNgen(inp_Keyword&);
    virtual void VisitNmap(inp_Keyword&);
    virtual void VisitNoCompression(inp_Keyword&);
    virtual void VisitNodalEnergyRate(inp_Keyword&);
    virtual void VisitNodalThickness(inp_Keyword&);
    virtual void VisitNode(inp_Keyword&);
    virtual void VisitNodeFile(inp_Keyword&);
    virtual void VisitNodeOutput(inp_Keyword&);
    virtual void VisitNodePrint(inp_Keyword&);
    virtual void VisitNodeResponse(inp_Keyword&);
    virtual void VisitNonStructuralMass(inp_Keyword&);
    virtual void VisitNormal(inp_Keyword&);
    virtual void VisitNoTension(inp_Keyword&);
    virtual void VisitNset(inp_Keyword&);
    virtual void VisitOrientation(inp_Keyword&);
    virtual void VisitOrnl(inp_Keyword&);
    virtual void VisitOutput(inp_Keyword&);
    virtual void VisitParameterShapeVariation(inp_Keyword&);
    virtual void VisitParameter(inp_Keyword&);
    virtual void VisitParameterDependence(inp_Keyword&);
    virtual void VisitPart(inp_Keyword&);
    virtual void VisitPeriodic(inp_Keyword&);
    virtual void VisitPeriodicMedia(inp_Keyword&);
    virtual void VisitPermeability(inp_Keyword&);
    virtual void VisitPhysicalConstants(inp_Keyword&);
    virtual void VisitPiezoelectric(inp_Keyword&);
    virtual void VisitPipeSoilInteraction(inp_Keyword&);
    virtual void VisitPipeSoilStiffness(inp_Keyword&);
    virtual void VisitPlanarTestData(inp_Keyword&);
    virtual void VisitPlastic(inp_Keyword&);
    virtual void VisitPlasticAxial(inp_Keyword&);
    virtual void VisitPlasticM1(inp_Keyword&);
    virtual void VisitPlasticM2(inp_Keyword&);
    virtual void VisitPlasticTorque(inp_Keyword&);
    virtual void VisitPorousBulkModuli(inp_Keyword&);
    virtual void VisitPorousElastic(inp_Keyword&);
    virtual void VisitPorousFailureCriteria(inp_Keyword&);
    virtual void VisitPorousMetalPlasticity(inp_Keyword&);
    virtual void VisitPostOutput(inp_Keyword&);
    virtual void VisitPotential(inp_Keyword&);
    virtual void VisitPrestressHold(inp_Keyword&);
    virtual void VisitPreTensionSection(inp_Keyword&);
    virtual void VisitPreprint(inp_Keyword&);
    virtual void VisitPressureEquationSolver(inp_Keyword&);
    virtual void VisitPressurePenetration(inp_Keyword&);
    virtual void VisitPressureStress(inp_Keyword&);
    virtual void VisitPrint(inp_Keyword&);
    virtual void VisitPsdDefinition(inp_Keyword&);
    virtual void VisitRadiate(inp_Keyword&);
    virtual void VisitRadiationFile(inp_Keyword&);
    virtual void VisitRadiationOutput(inp_Keyword&);
    virtual void VisitRadiationPrint(inp_Keyword&);
    virtual void VisitRadiationSymmetry(inp_Keyword&);
    virtual void VisitRadiationViewfactor(inp_Keyword&);
    virtual void VisitRandomResponse(inp_Keyword&);
    virtual void VisitRateDependent(inp_Keyword&);
    virtual void VisitRatios(inp_Keyword&);
    virtual void VisitReactionRate(inp_Keyword&);
    virtual void VisitRebar(inp_Keyword&);
    virtual void VisitRebarLayer(inp_Keyword&);
    virtual void VisitReflection(inp_Keyword&);
    virtual void VisitRelease(inp_Keyword&);
    virtual void VisitRemeshTrigger(inp_Keyword&);
    virtual void VisitResponseSpectrum(inp_Keyword&);
    virtual void VisitRestart(inp_Keyword&);
    virtual void VisitRetainedEigenModes(inp_Keyword&);
    virtual void VisitRetainedNodalDofs(inp_Keyword&);
    virtual void VisitRigidBody(inp_Keyword&);
    virtual void VisitRigidSurface(inp_Keyword&);
    virtual void VisitRotaryInertia(inp_Keyword&);
    virtual void VisitSectionControls(inp_Keyword&);
    virtual void VisitSectionFile(inp_Keyword&);
    virtual void VisitSectionOrigin(inp_Keyword&);
    virtual void VisitSectionPoints(inp_Keyword&);
    virtual void VisitSectionPrint(inp_Keyword&);
    virtual void VisitSelectCyclicSymmetryModes(inp_Keyword&);
    virtual void VisitSelectEigenmodes(inp_Keyword&);
    virtual void VisitSfilm(inp_Keyword&);
    virtual void VisitSflow(inp_Keyword&);
    virtual void VisitShear(inp_Keyword&);
    virtual void VisitShearCenter(inp_Keyword&);
    virtual void VisitShearFailure(inp_Keyword&);
    virtual void VisitShearRetention(inp_Keyword&);
    virtual void VisitShearTestData(inp_Keyword&);
    virtual void VisitShellGeneralSection(inp_Keyword&);
    virtual void VisitShellSection(inp_Keyword&);
    virtual void VisitShellToSolidCoupling(inp_Keyword&);
    virtual void VisitSimpedance(inp_Keyword&);
    virtual void VisitSimpleShearTestData(inp_Keyword&);
    virtual void VisitSlideLine(inp_Keyword&);
    virtual void VisitSload(inp_Keyword&);
    virtual void VisitSoils(inp_Keyword&);
    virtual void VisitSolidSection(inp_Keyword&);
    virtual void VisitSolubility(inp_Keyword&);
    virtual void VisitSolutionTechnique(inp_Keyword&);
    virtual void VisitSolverControls(inp_Keyword&);
    virtual void VisitSorption(inp_Keyword&);
    virtual void VisitSpatialDistribution(inp_Keyword&);
    virtual void VisitSpecificHeat(inp_Keyword&);
    virtual void VisitSpectrum(inp_Keyword&);
    virtual void VisitSpotWeld(inp_Keyword&);
    virtual void VisitSpotWeldInteraction(inp_Keyword&);
    virtual void VisitSpotWeldProperty(inp_Keyword&);
    virtual void VisitSpring(inp_Keyword&);
    virtual void VisitSradiate(inp_Keyword&);
    virtual void VisitStatic(inp_Keyword&);
    virtual void VisitSteadyStateCriteria(inp_Keyword&);
    virtual void VisitSteadyStateDetection(inp_Keyword&);
    virtual void VisitSteadyStateDynamics(inp_Keyword&);
    virtual void VisitSteadyStateTransport(inp_Keyword&);
    virtual void VisitStep(inp_Keyword&);
    virtual void VisitSubcycling(inp_Keyword&);
    virtual void VisitSubmodel(inp_Keyword&);
    virtual void VisitSubstructureCopy(inp_Keyword&);
    virtual void VisitSubstructureDelete(inp_Keyword&);
    virtual void VisitSubstructureDirectory(inp_Keyword&);
    virtual void VisitSubstructureGenerate(inp_Keyword&);
    virtual void VisitSubstructureLoadCase(inp_Keyword&);
    virtual void VisitSubstructureMatrixOutput(inp_Keyword&);
    virtual void VisitSubstructurePath(inp_Keyword&);
    virtual void VisitSubstructureProperty(inp_Keyword&);
    virtual void VisitSurface(inp_Keyword&);
    virtual void VisitSurfaceBehavior(inp_Keyword&);
    virtual void VisitSurfaceFlaw(inp_Keyword&);
    virtual void VisitSurfaceInteraction(inp_Keyword&);
    virtual void VisitSurfacePermeability(inp_Keyword&);
    virtual void VisitSurfaceProperty(inp_Keyword&);
    virtual void VisitSurfacePropertyAssignment(inp_Keyword&);
    virtual void VisitSurfaceOutput(inp_Keyword&);
    virtual void VisitSurfaceSection(inp_Keyword&);
    virtual void VisitSurfaceSmoothing(inp_Keyword&);
    virtual void VisitSwelling(inp_Keyword&);
    virtual void VisitSymmetricModelGeneration(inp_Keyword&);
    virtual void VisitSymmetricResultsTransfer(inp_Keyword&);
    virtual void VisitSystem(inp_Keyword&);
    virtual void VisitTemperature(inp_Keyword&);
    virtual void VisitTensileFailure(inp_Keyword&);
    virtual void VisitTensionCutoff(inp_Keyword&);
    virtual void VisitTensionStiffening(inp_Keyword&);
    virtual void VisitThermalExpansion(inp_Keyword&);
    virtual void VisitTie(inp_Keyword&);
    virtual void VisitTimePoints(inp_Keyword&);
    virtual void VisitTorque(inp_Keyword&);
    virtual void VisitTorquePrint(inp_Keyword&);
    virtual void VisitTracerParticle(inp_Keyword&);
    virtual void VisitTransform(inp_Keyword&);
    virtual void VisitTransportEquationSolver(inp_Keyword&);
    virtual void VisitTransportVelocity(inp_Keyword&);
    virtual void VisitTransverseShearStiffness(inp_Keyword&);
    virtual void VisitTriaxialTestData(inp_Keyword&);
    virtual void VisitTrs(inp_Keyword&);
    virtual void VisitTurbulenceModel(inp_Keyword&);
    virtual void VisitUndexChargeProperty(inp_Keyword&);
    virtual void VisitUelProperty(inp_Keyword&);
    virtual void VisitUniaxial(inp_Keyword&);
    virtual void VisitUniaxialTestData(inp_Keyword&);
    virtual void VisitUnloadingData(inp_Keyword&);
    virtual void VisitUserDefinedField(inp_Keyword&);
    virtual void VisitUserElement(inp_Keyword&);
    virtual void VisitUserMaterial(inp_Keyword&);
    virtual void VisitUserOutputVariables(inp_Keyword&);
    virtual void VisitUserSubroutines(inp_Keyword&);
    virtual void VisitVariableMassScaling(inp_Keyword&);
    virtual void VisitViewfactorOutput(inp_Keyword&);
    virtual void VisitVisco(inp_Keyword&);
    virtual void VisitViscoelastic(inp_Keyword&);
    virtual void VisitViscosity(inp_Keyword&);
    virtual void VisitViscous(inp_Keyword&);
    virtual void VisitVoidNucleation(inp_Keyword&);
    virtual void VisitVolumetricTestData(inp_Keyword&);
    virtual void VisitWave(inp_Keyword&);
    virtual void VisitWind(inp_Keyword&);

  protected:

    cow_String currentPartName;
    cow_String currentAssemblyName;
    cow_String currentInstanceName;
    cow_String currentStepName;
    int superpathLevel;

    cow_ListTranslatedString errors;
    cow_ListTranslatedString warnings;
    cow_ListTranslatedString fatalErrors;
};

#endif /* inp_Visitor_h */
