/*   -*- mode: c++ -*-   */
#ifndef kamO_TypeTable_h
#define kamO_TypeTable_h

// Begin local includes

#include <typ_TypeTables.h>
#include <typ_Architecture.h>
#include <kamO_FacilityTag.h>

//
// WARNING: Do not edit this file.
//          It was generated by ODT version 0.9.8
//



extern typ_ArchCompEntry kamO_ArchEntry();


// The following macros were extracted from the hand-coded kmaC_TypeTable.txt

#define TYP_TIX_kamO_ApiExtension		((TYP_FAC_kamO << 16) | 0x1)

#endif
