/*   -*- mode: c++ -*-   */
#ifndef kmaO_TypeTable_h
#define kmaO_TypeTable_h

// Begin local includes

#include <typ_TypeTables.h>
#include <typ_Architecture.h>
#include <kmaO_FacilityTag.h>

//
// WARNING: Do not edit this file.
//          It was generated by ODT version 0.9.8
//



extern typ_ArchCompEntry kmaO_ArchEntry();


// The following macros were extracted from the hand-coded kmaC_TypeTable.txt

#define TYP_TIX_kmaO_ApiExtension		((TYP_FAC_kmaO << 16) | 0x1)

#endif
